import Head from "next/head";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { SiGmail } from "react-icons/si";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import Image from "next/image";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import codup from "../public/codup.png";
import TPLInsurance from "../public/TPLInsurance.png";
import FAST from "../public/FAST.png";
import Sports from "../public/Sports.png";
import Insurance from "../public/Insurance.png";
import Missing from "../public/Missing.png";
import Trello from "../public/Trello.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Aahil Ashiq Ali Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/portfolio.png" type="image/png" sizes="32x32" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-end dark:text-white">
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="/CV.pdf"
                  download={true}
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Aahil Ashiq Ali
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Full Stack Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Seeking a Full Stack Developer role to leverage expertise in
              Python, JavaScript, React, Node.js, and databases. I am passionate
              about building scalable web applications, solving complex
              problems, and contributing to innovative projects in a dynamic
              environment.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                href="https://mail.google.com/mail/?view=cm&fs=1&to=aahilashiqali@gmail.com"
                target="_blank"
                rel="noopener noreferrer"
                aria-label="Linkedin"
              >
                <SiGmail />
              </a>
              <a
                href="http://www.linkedin.com/in/aahil-ashiq-ali-4510651a8"
                target="_blank"
                rel="noopener noreferrer"
                aria-label="Linkedin"
              >
                <AiFillLinkedin />
              </a>
              <a
                href="https://github.com/AahilAshiqAli"
                target="_blank"
                rel="noopener noreferrer"
                aria-label="Github"
              >
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image
                src={deved}
                layout="fill"
                objectFit="cover"
                className="rounded-full"
              />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-5xl">
              {" "}
              Experience
            </h3>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={codup}
                width={100}
                height={100}
                className="rounded-full"
              />
              <h3 className="text-lg  font-medium text-teal-600 pt-8">
                Mern Stack Intern
              </h3>
              <h2 className="p-0 m-0 text-md text-teal-600">CODUP</h2>
              <h2 className="pt-0 pb-5 m-0 text-sm">MARCH 2024 - PRESENT </h2>
              <p className="py-2">
                Facilitating the development of a cart-sharing feature within
                Extend Commerce, Codup Shopify plugin, using Gadget, to enable
                sharing among company employees based on defined roles and
                permissions
              </p>
              <h4 className="pt-4 text-teal-600">Skills Learned</h4>
              <div className="flex flex-wrap gap-2 mt-4 justify-center">
                <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">
                  Git
                </span>
                <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">
                  React JS
                </span>
                <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">
                  Node JS
                </span>
                <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">
                  MongoDB
                </span>
                <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">
                  Tailwind CSS
                </span>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={TPLInsurance}
                width={100}
                height={100}
                className="rounded-full"
              />
              <h3 className="text-lg font-medium text-teal-600 pt-8">
                Software IT Development Intern
              </h3>
              <h2 className="p-0 m-0 text-md text-teal-600">TPL INSURANCE</h2>
              <h2 className="pt-0 pb-5 m-0 text-sm">
                JUNE 2024 - AUGUST 2024{" "}
              </h2>
              <p className="py-2">
                Developed a Book Management System using ASP .NET FrameWork.
              </p>
              <p className="py-2">
                Facilitated comprehensive requirement gathering sessions for the
                development of a new Customer Relationship Management (CRM)
                system for TPL Insurance. These sessions involved in-depth
                discussions with the heads of various departments to thoroughly
                understand their specific needs and the underlying business
                logic, ensuring that the CRM solution would effectively address
                the company's operational goals and enhance cross-departmental
                collaboration.
              </p>
              <h4 className="pt-4 text-teal-600">Skills Learned</h4>
              <div className="flex flex-wrap gap-2 mt-4 justify-center">
                <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">
                  C#
                </span>
                <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">
                  ASP .NET
                </span>
                <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">
                  Figma
                </span>
                <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">
                  Requirement Gathering
                </span>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={FAST}
                width={100}
                height={100}
                className="rounded-full"
              />
              <h3 className="text-lg font-medium text-teal-600 pt-8">
                OBJECT ORIENTED PROGRAMMING LAB ASSISTANT
              </h3>
              <h2 className="pt-0 pb-5 m-0 text-sm">JAN 2024 - JUNE 2024 </h2>
              <p className="py-2">
                Guided students during lab sessions, assisted with debugging
                code, and evaluated programming assignments in the
                Object-Oriented Programming course.
              </p>
              <h4 className="pt-4 text-teal-600">Skills Learned</h4>
              <div className="flex flex-wrap gap-2 mt-4 justify-center">
                <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">
                  Object Oriented Programming
                </span>
                <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">
                  Debugging
                </span>
              </div>
              <h3 className="text-lg font-medium text-teal-600 pt-8">
                DESIGN AND ANALYSIS OF ALGORITHMS TEACHER ASSISTANT
              </h3>
              <h2 className="pt-0 pb-5 m-0 text-sm">JAN 2024 - JUNE 2024 </h2>
              <p className="py-2">Evaluated Assignments and quizes</p>
              <h4 className="pt-4 text-teal-600">Skills Learned</h4>
              <div className="flex flex-wrap gap-2 mt-4 justify-center">
                <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">
                  Algorithms
                </span>
                <span className="bg-gray-200 text-gray-800 px-3 py-1 rounded-full text-sm">
                  Evaluating Assignments
                </span>
              </div>
            </div>
          </div>
        </section>
        <section className="py-10">
          <h3 className="text-3xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-5xl ">
            Projects
          </h3>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <a
                href="https://github.com/AahilAshiqAli/Missing-Object-Detection"
                target="_blank"
                rel="noopener noreferrer"
                class="relative block overflow-hidden rounded-lg group"
              >
                <Image
                  className="rounded-3xl object-contain object-top transition duration-300 ease-in-out group-hover:blur-sm group-hover:opacity-50 "
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Missing}
                />
                <div class="absolute inset-0  flex items-center justify-center opacity-0 group-hover:opacity-100 transition duration-300 ease-in-out">
                  <p class="text-gray-700 text-lg font-semibold p-4 text-center">
                    The <b> Missing Object Detector </b> utilizes YOLO for image
                    localization and object detection within a room. The system
                    generates accurate bounding boxes around identified objects,
                    allowing users to track their locations in real-time. Users
                    can see objects that have been found at any point in history
                    directly from their dashboard or landing page. Additionally,
                    a secure login and logout system has been implemented.
                    <br />
                    DEMO AVAILABLE ON GITHUB
                    <br />
                    <br />
                    DJANGO, PYTHON, HTML, CSS, JAVASCRIPT, SQLITE
                  </p>
                </div>
              </a>
            </div>

            <div className="basis-1/3 flex-1 ">
              <a
                href="https://github.com/AahilAshiqAli/Sports-App"
                target="_blank"
                rel="noopener noreferrer"
                class="relative block overflow-hidden rounded-lg group"
              >
                <Image
                  className="rounded-3xl object-contain object-top transition duration-300 ease-in-out group-hover:blur-sm group-hover:opacity-50 "
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Sports}
                />
                <div class="absolute inset-0  flex items-center justify-center opacity-0 group-hover:opacity-100 transition duration-300 ease-in-out">
                  <p class="text-gray-700 text-lg font-semibold p-4 text-center">
                    The <b>Sports App </b> displays upcoming match schedules and
                    past match results, offering users a seamless way to stay
                    updated. The app includes features for filtering and sorting
                    matches, enabling users to easily find relevant information
                    based on their preferences.
                    <br />
                    DEMO AVAILABLE ON GITHUB
                    <br />
                    <br />
                    DJANGO, PYTHON, HTML, CSS, JAVASCRIPT, SQLITE
                  </p>
                </div>
              </a>
            </div>

            <div className="basis-1/3 flex-1 ">
              <a
                href="https://github.com/AahilAshiqAli/Insurance-CRM-FrontEnd"
                target="_blank"
                rel="noopener noreferrer"
                class="relative block overflow-hidden rounded-lg group"
              >
                <Image
                  className="rounded-3xl object-cover object-top transition duration-300 ease-in-out group-hover:blur-sm group-hover:opacity-50 "
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Insurance}
                />
                <div class="absolute inset-0  flex items-center justify-center opacity-0 group-hover:opacity-100 transition duration-300 ease-in-out">
                  <p class="text-gray-700 text-lg font-semibold p-4 text-center">
                    Our <b>Insurance CRM</b> simplifies the device insurance
                    process by automating product setup, policy creation, and
                    premium calculation, making it accessible to all users. It
                    features a user-friendly interface for insuring devices like
                    phones and laptops, with AI-powered chatbot assistance for
                    real-time support. The platform streamlines coverage
                    options, document uploads, and provides a transparent,
                    hassle-free experience.
                    <br />
                    <br />
                    <br />
                    REACT JS, EXPRESS JS, SQL
                  </p>
                </div>
              </a>
            </div>

            <div className="basis-1/3 flex-1 ">
              <a
                href="https://github.com/AahilAshiqAli/Trello"
                target="_blank"
                rel="noopener noreferrer"
                class="relative block overflow-hidden rounded-lg group"
              >
                <Image
                  className="rounded-3xl object-cover object-top transition duration-300 ease-in-out group-hover:blur-sm group-hover:opacity-50 "
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Trello}
                />
                <div class="absolute inset-0  flex items-center justify-center opacity-0 group-hover:opacity-100 transition duration-300 ease-in-out">
                  <p class="text-gray-700 text-lg font-semibold p-4 text-center">
                    <b> Sample Trello App </b> is a to-do list app with
                    drag-and-drop support, allowing users to create, edit,
                    delete, and manage tasks easily. It uses Zustand for state
                    management and React Query for real-time data handling.
                    <br />
                    <br />
                    REACT, ZUSTAND, REACT QUERY, JAVASCRIPT
                  </p>
                </div>
              </a>
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
